### ISSUE TITLE
[Question] Can you set a static height in the nodes

### ISSUE THREAD

**Issue by PabloTheDarkLord** [diogofcunha/react-virtualized-tree#101]
Hello,
I'm trying to create a simple tree, but I don't need auto sizing at node level. So I'm trying to change the auto height using:

`<div style={style} className={classes.dividerStyle}>
                    <div className={'tree'} style={{ height: this.setHeight(rowIndex), maxHeight: 600 }}>
                        <Tree nodes={this.state.data} onChange={this.handleChange} >
                            {({ style, ...p }) =>
                                <div style={{height: 40,
                                left: style.left, 
                                position: 'absolute', 
                                top: 40 * p.index, width: style.width, marginLeft: style.marginLeft, cursor: style.cursor, userSelect:style.userSelect}
                                }>{
                                    createNodeRenderer([Expandable], p, columnIndex)
                                }
                                </div>
                            }
                        </Tree>
                    </div>
                </div>`

but looks like the top: 40 * p.index. is not working on scrolling the tree, because I set a max height, my question is there is a way to set the a static node height?

Thanks,

**Comment by diogofcunha** [comment]
Hey @PabloTheDarkLord there is nothing stopping that from happening, as you can see in the examples nodes will adapt to the heigh you use for the container of your nodes. 

I can't understand that code as it isn't even formatted, but your css looks strange, you should not need any top or to position your nodes as absolute

**Comment by LukaszGrela** [comment]
I know it is closed:) but have the same problem (documentation update would be great to describe this task).

I have a `Tree` component with custom row :
```
                        <TreeNode
                          style={style}
                          node={node}
                          {...rest}
                          onClick={(): void => {
                            this.props.onHandleExpand(node);
                          }}
                          expanded={expanded}
                          expandable={expandable}
                          leaf={leaf}
                          selected={selected}
                          selectable={selectable}
                        >
```
`style`, `node` and `...rest` comes from the `Tree`. The `style` tells the `height` of the element. In my case it is 28px. I need to change it, what drives that value? How can I change the height of the tree elements (I want all of them to be equal height, no dynamic resizing).
