### ISSUE TITLE
 Is there a detailed document? I found this performance to be very good. But I can't use it well in real projects.

### ISSUE THREAD

**Issue by DawnL6** [diogofcunha/react-virtualized-tree#113]

**Comment by diogofcunha** [comment]
Hi @DawnL6.

The API layer for this project is very small, all the documentation you may need can be found at https://diogofcunha.github.io/react-virtualized-tree/#/examples/basic-tree.

If you're having performance issues in a project there are several factors that can contribute to that, especially the way you handle updates in state, it's really hard to have any answers without a real example to replicate.

Cheers
Diogo
