### ISSUE TITLE
Question: What drives the height of the tree element and how to change it

### ISSUE THREAD

**Issue by LukaszGrela** [diogofcunha/react-virtualized-tree#115]
I have a Tree component with custom row :
```
                        <TreeNode
                          style={style}
                          node={node}
                          {...rest}
                          onClick={(): void => {
                            this.props.onHandleExpand(node);
                          }}
                          expanded={expanded}
                          expandable={expandable}
                          leaf={leaf}
                          selected={selected}
                          selectable={selectable}
                        >
```
`style`, `node` and `...rest` comes from the `Tree`. The `style` tells the `height` of the element. In my case it is `28px`. I need to change it, what drives that value? How can I change the `height` of the tree elements (I want all of them to be equal height, no dynamic resizing).

It is a `Tree` that gives rows `height` in the `style` object. How the `Tree` knows what `height` to pass and how one could change it. Documentation update would be great to describe this task.

**Comment by LukaszGrela** [comment]
Ok, so the height of the row seems to be coming from the content height. So what I had to do is to wrap the row content with a wrapper div, and apply height on that element. This could be added to the documentation somewhere :)

**Comment by diogofcunha** [comment]
This can be found at https://diogofcunha.github.io/react-virtualized-tree/#/examples/node-measure. Thanks @LukaszGrela
