### ISSUE TITLE
Feature Request: FilteringContainer allow to pass predicate function

### ISSUE THREAD

**Issue by LukaszGrela** [diogofcunha/react-virtualized-tree#117]
I have a tree that has some filterable props besides the name, I would like the filtering to work not only on the `name` but on my custom props too (or state etc.). It would be useful if the `FilteringContainer` could allow to pass custom filter method.

You already have
```
const nameMatchesSearchTerm = searchTerm => ({name}) => {
  const upperCaseName = name.toUpperCase();
  const upperCaseSearchTerm = searchTerm.toUpperCase();

  return upperCaseName.indexOf(upperCaseSearchTerm.trim()) > -1;
};
```
so if we could pass the predicate as `(node:FlattenedNode)=>boolean` that would be great.

**Comment by diogofcunha** [comment]
sorry for the delay @LukaszGrela.

`3.4.0` has that option enabled
