### ISSUE TITLE
Collapse onClick instead of onDoubleClick posibility

### ISSUE THREAD

**Issue by underfisk** [diogofcunha/react-virtualized-tree#120]
I've encountered that there is no way of allowing group collapses by single click, i think this might be cool to choose single or double.

**Comment by diogofcunha** [comment]
Hi @underfisk, as this tree takes no major assumptions on Expandability, all you need to do is create your own renderer just like https://github.com/diogofcunha/react-virtualized-tree/blob/master/src/renderers/Expandable.js but attach a single click instead if that makes sense for your usecase 🙂
