### ISSUE TITLE
Filterable component search

### ISSUE THREAD

**Issue by underfisk** [diogofcunha/react-virtualized-tree#121]
I have been trying to change the search component, i can via css but using MaterialUI i would like to use a react component instead of manipulating the css outside.
Is there any way you could provide the input being provided via props and propagate the changes through onChange callback?

**Comment by diogofcunha** [comment]
Hi @underfisk, the source code for the filtering container is quite tiny, you can always create your own custom component that based on https://github.com/diogofcunha/react-virtualized-tree/blob/master/src/FilteringContainer.js and render whatever piece of UI feels right to your usecase
