### ISSUE TITLE
npm version is not the latest version

### ISSUE THREAD

**Issue by franciscofabian** [diogofcunha/react-virtualized-tree#122]
The version published on npm is 3.2.3 while the latest version is 3.3.0, is there a reason for this?

**Comment by diogofcunha** [comment]
hey @franciscofabian, It's because I enabled 2FA and it crashed the automatic releases, I'm going to update later, thanks

**Comment by diogofcunha** [comment]
Done @franciscofabian. Thanks.

Just be aware that what has (chore) is not meant to be published to npm until either a feature or a fix is landed on master 🙂
