### ISSUE TITLE
Search debounce

### ISSUE THREAD

**Issue by underfisk** [diogofcunha/react-virtualized-tree#126]
A nice thing to have is debouncing because onChange triggers re-render while typing and using debounce will avoid such a thing.
Do you think it is possible to integrate or is there an external way to interact without modifying the plugin externally?

**Comment by diogofcunha** [comment]
Hi @underfisk.

That's actually supported already, have a look at the type definition in https://github.com/diogofcunha/react-virtualized-tree/blob/master/index.d.ts#L101.

You can supply a custom debouncer as a prop to the filtering container

**Comment by underfisk** [comment]
Do you have any example on how to interact with the debouncer parameter because it's quite confusing
