### ISSUE TITLE
Why jest is declared as dependency? Why not it's in devDependency?

### ISSUE THREAD

**Issue by rgilmutdinov** [diogofcunha/react-virtualized-tree#133]
Hi! 
I've added `react-virtualized-tree` to my project and I'm seeing `jest` in dependency.
I believe that because of jest is required as a production dependency might be causing a problems in some cases. Is there a particular reason for it not to be in devDependencies?

**Comment by diogofcunha** [comment]
Thanks for reporting @rgilmutdinov.

Has been fixed now
