### ISSUE TITLE
Proposal: documentation improvements

### ISSUE THREAD

**Issue by kvolkovich-sc** [diogofcunha/react-virtualized-tree#18]
Hi! We want to use your react tree implementation in our [filemanager](https://github.com/OpusCapita/filemanager) and maybe for some of other react components. 

**You made a great job!**

We documenting our react components using [react-showroom](https://github.com/OpusCapita/react-showroom-client)

It allows us to play with code sandbox in real-time. Sometimes it useful for better understand what each component property do.

How do you think, it would be useful to use react-showroom or some similar tool for your project or not?

**Comment by diogofcunha** [comment]
Hi @kvolkovich-sc.

Thank you, and I hope you enjoy using this library, I'm glad it address some of your requirements.

I was actually thinking about that lately, having a rich way to interact with the components on real time is great.

In the past, other libraries I contributed to had a few problems with those kind of approaches, when user started to edit the components a little bit out of the most basic use cases or when dealing with bigger data collection those kind of interactive examples were giving a really bad user experience to the user, most times the page would even become unresponsive.

**The 2 options I was considering for this were what you proposed or auto-deploy the examples to a jsfiddle and expose that link in the example page.**

I may need a few days and a few more opinions in here to decide what to do, and I will also need to play around with it a little bit.

**Comment by kvolkovich-sc** [comment]
I haven't seen performance/UX issues, maybe it cause I have no a lot experience in developing of complex grids, or similar complex component with a big(?) data.  As I see, you work a lot with [grids](https://diogofcunha.github.io/react-data-grid-extensions).

Agree, jsfiddle can be a good simple choice in your case.

**Comment by diogofcunha** [comment]
I work with them everyday :blush:

That one is just a repo I created to have some ready to go code snippets to address any doubts on my companies open source project (react-data-grid), that project is an example of a place where we used to have a interactive playground and needed to move away from it due to severe performance issues.

I will give a try to use your project and let you know, just a quick question, do you denounce the interactions with the editor in some manner?

**Comment by kvolkovich-sc** [comment]
Do you mean **debounce**?

**Comment by diogofcunha** [comment]
Yes, that's what I meant, the auto corrector betrayed me.

I will have a look, an option that doesn't refresh the dom automatically could be a good way to go.

**Comment by kvolkovich-sc** [comment]
OK. I'll add "Autoplay" (or something like) option it closer to this weekend.
