### ISSUE TITLE
CellMeasurer issue

### ISSUE THREAD

**Issue by bini1988** [diogofcunha/react-virtualized-tree#26]
I have problem when nodes with different height are rendered. The [NodeRenderer ](https://github.com/diogofcunha/react-virtualized-tree/blob/fb42417b1b91f6fc87426d1f956901b6a1aff752/src/Tree.js#L22)component does not receive a measure prop as I expect. The problem maybe in initial parameters of [CellMeasurerCache](https://github.com/diogofcunha/react-virtualized-tree/blob/fb42417b1b91f6fc87426d1f956901b6a1aff752/src/Tree.js#L8) object, I supoose to use defaultHeight insteade of minHeight. Please, fix it.

**Comment by diogofcunha** [comment]
Hi @bini1988 the CellMeasurer is not part of the current stable version. It's about to be released in v2.

Will publish a beta version soon and let you know and the stable version will be released probably in maximum 2 weeks time.

**Comment by bini1988** [comment]
Ok, thunks for responce

**Comment by diogofcunha** [comment]
@bini1988 a tag for 2.0.0 is now published, you install it via npm:

`npm i react-virtualized-tree@next`

That version also ships with severe performance improvements, just take notice that some public api  may break before the official release, but I will try to keep any changes to a bare minimum on that part.

**Comment by hinst** [comment]
Can u please tell me if its posible to have rows with fixed height using current stable version? 
For example, all rows 40px, but not 20px. Currently all rows have height=20px

**Comment by diogofcunha** [comment]
Hi @hinst.

It isn't.

I will publish v2 over the weekend or even before if I find the time. I just want to add another PR in to reduce the bundle size.
