### ISSUE TITLE
Screenshots and examples

### ISSUE THREAD

**Issue by justinlawrence** [diogofcunha/react-virtualized-tree#31]
A few screenshots and examples would go a long way.

**Comment by diogofcunha** [comment]
Hi Justin, probably the readme need to be tweaked as you couldn't find the link to the examples.

They can be found in here https://diogofcunha.github.io/react-virtualized-tree/#/examples/basic-tree

**Comment by justinlawrence** [comment]
Hey Diogo, thanks for the quick reply. I've submitted a PR with a basic screenshot, as well as an updated link.

![react-virtualized-tree](https://user-images.githubusercontent.com/1521183/37708046-14cf3fb4-2cfd-11e8-9fad-8c0d557397cd.gif)

**Comment by diogofcunha** [comment]
Thanks for your valuable contribution @justinlawrence and nice catch, it will probably be important to grow the user set.
