### ISSUE TITLE
There's no way user can change rowHeight without forking PR

### ISSUE THREAD

**Issue by philipyoungg** [diogofcunha/react-virtualized-tree#33]
Can I send a PR so user can set minHeight and rowHeight on `cellMeasurer`?

**Comment by diogofcunha** [comment]
Hi phil, what's the use case? What's the version you're using?

You shouldn't need that, the idea of the cellMeasurer is that it your row heights will adapt the the content height.

**Comment by philipyoungg** [comment]
Currently my cell have fixed height—which is 58px. 

I have the latest one, but after reading from node modules, it looks like the the build vs source code on Github is different. On Github it shows minHeight, while on build it shows height. 

Also I don't get this.props.measure prop on NodeRenderer which documentation says it should be there. 

So that's my use case!

**Comment by diogofcunha** [comment]
Hey @philipyoungg.

As explained in https://github.com/diogofcunha/react-virtualized-tree/issues/26 that code will be released on 2.0.0 as it introduces some breaking changes, you can use `next`

**Comment by philipyoungg** [comment]
Looks like there's an issue on the `@next`.

No code found on `node_modules`
<img width="401" alt="screen shot 2018-04-05 at 3 01 47 pm" src="https://user-images.githubusercontent.com/11477718/38351507-59d49334-38e2-11e8-8386-30773f4b59cb.png">

**Comment by diogofcunha** [comment]
Hmm, you're absolutely correct.

There must have been a problem in the publish, can see in here https://unpkg.com/react-virtualized-tree@2.0.0/

Will re publish as soon as I arrive home

**Comment by diogofcunha** [comment]
Republished and looking good at https://unpkg.com/react-virtualized-tree@next
