### ISSUE TITLE
Module not found: Can't resolve 'react-virtualized-tree' @2.0.0

### ISSUE THREAD

**Issue by weilonge** [diogofcunha/react-virtualized-tree#34]
Hi! First, thank you for working this great component!
2.0.0 has the left-margin customization feature, but it seems not published to NPM yet. So I tried to install this by this command:
`yarn add react-virtualized-tree@2.0.0`

The error message is like this while compiling:
`Module not found: Can't resolve 'react-virtualized-tree'`

Can you help me to fix the issue? Thanks.

**Comment by diogofcunha** [comment]
Hi.

2.0.0 it's still a tag, you need to do yarn add react-virtualized-tree@next
