### ISSUE TITLE
Requesting dynamic row height feature

### ISSUE THREAD

**Issue by AvanthikaMeenakshi** [diogofcunha/react-virtualized-tree#35]
Hey, I would love to pass minHeight as a prop to <TreeContainer ../> which can later be fed into CellMeasurerCache of <Tree .. />, because minHeight of the tree node varies from to tree to tree in my application.. Would you like if I do that and raise a PR?

**Comment by diogofcunha** [comment]
Hi @AvanthikaMeenakshi.

Any blocker, when using https://unpkg.com/react-virtualized-tree@2.0.0-beta1/lib/index.js of setting that on the Renderer for the tree itself? the measuerer should adapt to your row height automatically, doesn't it work for you?

**Comment by AvanthikaMeenakshi** [comment]
Hey @diogofcunha , when will this be released officially? Shall we still use this in production?

**Comment by diogofcunha** [comment]
Hey.

I wanna find some time to finish bulk actions and replace the context api used at this moment.

It's fine to use it in production, I don't predict any breaking changes before the oficial release
