### ISSUE TITLE
Typo in exports  in /selectors/nodes file

### ISSUE THREAD

**Issue by smoleniuch** [diogofcunha/react-virtualized-tree#37]
I wanted to create custom expadable component based on the docs example.I have encountered typo in mentioned file.It is weird for me that i have different content inside of my `node_module/react-virtualized-tree` compare to github master branch.

I have installed it through npm by `npm install react-virtualized-tree`.And i can see that it is `1.2.5` version

You can check this [codesandbox](https://codesandbox.io/s/884xwzoo19) example for clarification.

**Comment by diogofcunha** [comment]
Hi @smoleniuch.

That's easy to explain, master has @next and not @1.2.5 code, is imminent and master has the code that will be released as part of version 2.0.0, that will happen later this week.

I'm not sure what's the problem in your code, but take note that react-virtualized-tree has a peer dependency with `react-virtualized`, to use it you should install react-virtualized too as part of your application.

The mentioned issue was fixed at https://github.com/diogofcunha/react-virtualized-tree/pull/24/files.

I would recommend you to run `npm install react-virtualized-tree@next`, that version should be stable enough now and has several improvements over the version your using

**Comment by smoleniuch** [comment]
Thanks @diogofcunha for clarification.

Cheers!
