### ISSUE TITLE
JEST Test Failure

### ISSUE THREAD

**Issue by SethGoodLuckMartin** [diogofcunha/react-virtualized-tree#43]
Hello there, I was hoping to get some insight on how to handle testing around react-virtualized-tree. I'm using JEST for testing and seem to be running into the following error when running unit tests. 

```
src/components/App.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'Expandable' of undefined
```

I was curious if you've seen this before and had perspective on how to handle. 
For added clarity, it is behaving as expected in app. So I suspect this may be related to JEST.

**Comment by SethGoodLuckMartin** [comment]
This was rectified by bringing the following line into the render method. 

`const { Expandable } = Renderers;` 

Keeping it outside was causing the JEST failure.

**Comment by diogofcunha** [comment]
Hmm, that is strange, was the component mounting or was it just a jest problem?

**Comment by diogofcunha** [comment]
I can try to replicate later as this is not expected at all and the component is tested internally with jest too without any issues.

Do you mind sharing your config?

**Comment by SethGoodLuckMartin** [comment]
Originally, I was declaring the constant outside of the class which was fine for running. 
I think JEST may not have fully reconciled global variables in the same way? 
So placing the constant inside of the render method had it mount appropriately. 

No need to replicate at this point if you'd rather focus on something else. 
Otherwise, I can pull it together for you. 

If no one else has had this issue, I'm fine giving you your time back! :)
