### ISSUE TITLE
Issues with keyboard navigation 

### ISSUE THREAD

**Issue by plumpNation** [diogofcunha/react-virtualized-tree#54]
- Each node is set to expandable. Can be solved with a custom renderer, however, maybe if there is no children, the tabindex should be set to -1
- When using the ENTER key to open and close the tree branches, or select a leaf node, focus is completely lost. (See EDIT below)
- SPACEBAR should be supported as a secondary way to open and close branches.

EDIT: I think the focus is lost due to the use of the anonymous function that renders the custom node. So that probably isn't an issue with this library. I'll leave it here just for history.

**Comment by diogofcunha** [comment]
Hi.

It may be that the focus could be better managed, I will have a look later to see what can be done.

Thanks for the feedback

**Comment by plumpNation** [comment]
Thanks for the library. It's much appreciated.

**Comment by diogofcunha** [comment]
Added a keyboard navigation example at (https://diogofcunha.github.io/react-virtualized-tree/#/examples/keyboard-nav) and fixed a tiny bug as part of version 3.0.1
