### ISSUE TITLE
All FilteringContainer props' types are required

### ISSUE THREAD

**Issue by Salasar** [diogofcunha/react-virtualized-tree#59]
Hi @diogofcunha! I started using your library, but came across the following issue: `FilteringContainerProps` interface in `index.d.ts` file has all props set as required, despite some of them are marked as optional here https://diogofcunha.github.io/react-virtualized-tree/#/docs/filtering. Is it a bug?

**Comment by diogofcunha** [comment]
Hello Salazar.

They are wrong, can you please open a pr to fix it? Otherwise I'll do it in the next few days

**Comment by diogofcunha** [comment]
Hi @Salasar.

Thanks for reporting this issue.

This is fixed and was released as part of `2.3.2`

**Comment by Salasar** [comment]
@diogofcunha sorry, I didn't have time to fix it on my own. Thank you for the fix!
