### ISSUE TITLE
Toggling parent node with filtered children will delete child nodes on removal of filter term. 

### ISSUE THREAD

**Issue by sjcasey21** [diogofcunha/react-virtualized-tree#60]
Found this bug in a project im working on and noticed its present in the example code as well. When using the filtering container any action that triggers an onChange() call in a renderer that invokes updateNode() will remove any child nodes that had been filtered out by the filtering container.

You can replicate the issue like this.
* expand a tree to a node with multiple child nodes.
* enter a filter term that removes several of the child nodes.
* toggle/update the parent node
* remove the filter term

the child nodes that had been filtered out will not return once the filter term has been removed.

**Comment by wheelibin** [comment]
I am also struggling with this bug. Thanks for fixing @sjcasey21!

@diogofcunha Any chance of getting this released?

Thanks :)

**Comment by diogofcunha** [comment]
Released, thanks 🚀

**Comment by wheelibin** [comment]
@diogofcunha Fantastic! Thanks very much, just tested it and it's working a treat.

@sjcasey21 Thanks again for getting a fix in too :)
