### ISSUE TITLE
The example "Nodes with auto measure" not renders correctly when expanding Argentina and Leo Messi Nodes

### ISSUE THREAD

**Issue by shilcare** [diogofcunha/react-virtualized-tree#64]
When expanding `Argentina`, and then `Leo Messi`, the content are rendered like a mess.

**Comment by diogofcunha** [comment]
Hi @shilcare what is the browser in use? it seems fine on latest chrome

**Comment by diogofcunha** [comment]
Closing due to lack of reply

**Comment by shilcare** [comment]
> Hi @shilcare what is the browser in use? it seems fine on latest chrome

I'm using latest chrome on macOS 10.14.2. Here is the screenshot.

<img width="643" alt="screen shot 2019-01-15 at 9 45 55 pm" src="https://user-images.githubusercontent.com/648413/51184400-28218500-190f-11e9-8c34-aae5977c5a6f.png">
