### ISSUE TITLE
Feature: expand nodes

### ISSUE THREAD

**Issue by jmavila** [diogofcunha/react-virtualized-tree#76]
Hi,

thanks for this nice component! I'm testing it and works really well. I've got one question about the expanding of nodes: can we expand all/ expand single nodes programmatically? There are cases where I want to render the full tree expanded at the beginning but I can only see the root node. Maybe I'm missing something but I couldn't figure out how to achieve this with the current API or documentation.

Thanks in advance!

**Comment by NicoleRauch** [comment]
Yes, this can be done. Simply add to each node the attribute
```
state: {
            expanded: true,
       }
```
and it will be expanded.

**Comment by jmavila** [comment]
Thanks a lot @NicoleRauch ! :+1:
