### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by INTACT180** [diogofcunha/react-virtualized-tree#81]
I was wondering if there was anyway to support animation with react virtualized tree upon expansion and collapsing to provide smooth transitions?

**Comment by diogofcunha** [comment]
Hi @INTACT180.

Nothing should stop you from adding animations, you just need to create your own renderer and add your animations in there.

Check the custom renderer example https://diogofcunha.github.io/react-virtualized-tree/#/examples/customize-renderers
