### ISSUE TITLE
[Question] Possible to pass nodes without an ID?

### ISSUE THREAD

**Issue by karangarg45** [diogofcunha/react-virtualized-tree#92]
Is it possible to use this tree without passing an ID with each node. Is there a way that tree can generate an automatic id for each node?

**Comment by diogofcunha** [comment]
Hi @karangarg45.

Not ATM, generating automatic ids can be tricky and to be done properly would probably damage performance for bigger trees, it's always safer if you do it on your side and have full control over the ids. Let me thing about this.

**Comment by diogofcunha** [comment]
Decided to not support this as Id are an integral part of the tree flow and update algorithms.
