### ISSUE TITLE
Expandable props unnecessarily required

### ISSUE THREAD

**Issue by eulertour** [diogofcunha/react-virtualized-tree#94]
Launching the documentation page via `npm install && npm start` results in several errors related to the `Expandable` renderer at `http://localhost:3000/#/examples/basic-tree`:
```
Warning: Failed prop type: The prop `onChange` is marked as required in `Expandable`, but its value is `undefined`.

Warning: Failed prop type: The prop `node.deepness` is marked as required in `Expandable`, but its value is `undefined`.

Warning: Failed prop type: The prop `index` is marked as required in `Expandable`, but its value is `undefined`.
```
It seems that `onChange` should be marked optional, but I don't know what to make of the other two missing props.

**Comment by eulertour** [comment]
On a related note, there seems to be an inconsistency between the docs and source on what is passed to the `onChange` prop. The description of `onChange` from the docs reads:

> to be invoked with the updated node and the update type

but in the "Basic Tree" example, it seems to be called with all of the nodes in the updated tree:
https://github.com/diogofcunha/react-virtualized-tree/blob/831ba2df74c4c09fd78e847aa250cfb4c367623c/demo/src/examples/Basic/index.js#L41-L43

**Comment by diogofcunha** [comment]
Hi @eulertour 

Those props are throwing because of the function `getRenderedComponentTree` that is used to get the stringified output, it's not important as it is specific to the example.

Those 3 props are required and the component wont work if they are not supplied.
