### ISSUE TITLE
TreeContainer doesn't pass width prop to Tree

### ISSUE THREAD

**Issue by eulertour** [diogofcunha/react-virtualized-tree#95]
#56 added an optional `width` prop to `Tree` and `TreeContainer`, but `TreeContainer` doesn't pass the prop to `Tree`. As a result, there's no way to enable horizontal scrolling.

**Comment by MarceloFonseca** [comment]
Just stepped into this issue as well on my quest for horizontal scrolling. :)

**Comment by diogofcunha** [comment]
Thanks to both.

This will be published on 3.2.1
