### ISSUE TITLE
Last child class not applied in Expandable renderer

### ISSUE THREAD

**Issue by karangarg45** [diogofcunha/react-virtualized-tree#97]
In Expandable renderer, user can pass a iconsClassNameMap property. In this even if i pass the lastChild class in the map the icon never appears.
The reason being icon only appears if the node has children. Logic @ https://github.com/diogofcunha/react-virtualized-tree/blob/master/src/renderers/Expandable.js#L32
This leads to the bug of no icon beside the leaf node.

**Comment by diogofcunha** [comment]
Hi @karangarg45.

Expandable renderer works like that by design, it is not intended to render an icon when there are no children.

If this doesn't fit your use case you can always create a custom render that fits it.
