### ISSUE TITLE
Typings issue with FilteringContainer props

### ISSUE THREAD

**Issue by karangarg45** [diogofcunha/react-virtualized-tree#98]
Filtering containter accepts nodes as props but this is not included in the typings file
https://github.com/diogofcunha/react-virtualized-tree/blob/master/index.d.ts#L97
Also FilteringContainter return node as an object to the render prop method but this is defined as `children: (nodes: Node[]) => JSX.Element;` in the typings file

**Comment by diogofcunha** [comment]
Thanks for reporting @karangarg45 

Fixed on version `3.2.3`
